DROP TABLE IF EXISTS packages;

CREATE TABLE packages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    version TEXT NOT NULL,
    dependencies TEXT NOT NULL
);
